#!/usr/bin/python3


# script to query for fan speed and to set fan on or off
import socket
import sys

PORT = 9099 # Change this in both the scripts to the same number if clashing with some other port on system

def print_help():
    msg = "\nPi Fan Control Utility\n\nUSAGE:\nfanctl <command>\n\nCOMMANDS:\n\nstatus (or no command)\t\tView Fan Status\ntoggle\t\t\t\tToggle fan ON or OFF\nhelp\t\t\t\tView this help\n"
    print(msg)
    exit()

if __name__ == "__main__":
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = socket.gethostname()
    port = PORT
    client.connect((host, port))
    if len(sys.argv) == 1:
        client.send("status".encode('ascii'))
    elif len(sys.argv) == 2:
        if sys.argv[1] == "help":
            print_help()
        else:
            client.send(sys.argv[1].encode('ascii'))
    else:
        print("Invalid number of arguments!")
    msg = client.recv(2048)
    print(msg.decode('ascii'))

